# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Breakfast
email: patrick@devlocker.io
description: >
  Breakfast integrates modern Javascript tooling into your Rails project.

  Get support for ES6 syntax & modules, live reload for CSS, JS, & HTML, and
  NPM support. Be up and running on the latest frontend framework in minutes.
baseurl: ""
url: "http://breakfast.devlocker.io"
twitter_username: patkoperwas
github_username:  patkoperwas

# Build settings
markdown: kramdown
exclude: [node_modules]
